### ISSUE TITLE
Have not been able to run psiturk using Anaconda 

### ISSUE THREAD

**Issue by angelaradulescu** [conda-forge/psiturk-feedstock#5]
Hi, 

I attempted installing Psiturk in a new Anaconda environment with no luck so far. 

Just to re-trace the steps: 

> conda create --name psiturk2 python=2.7 anaconda pip
> source activate psiturk2
> conda install -c conda-forge psiturk

Then when running psiturk, I got this error: 

> Traceback (most recent call last):
>   File "/home/angelar/envs/psiturk/bin/psiturk", line 6, in <module>
>     sys.exit(psiturk.command_line.process())
>   File "/home/angelar/envs/psiturk/lib/python2.7/site-packages/psiturk/command_line.py", line 15, in process
>     launch_shell()
>   File "/home/angelar/envs/psiturk/lib/python2.7/site-packages/psiturk/command_line.py", line 105, in launch_shell
>     import psiturk.psiturk_shell as ps
>   File "/home/angelar/envs/psiturk/lib/python2.7/site-packages/psiturk/psiturk_shell.py", line 21, in <module>
>     import readline
> ImportError: /home/angelar/envs/psiturk/lib/python2.7/lib-dynload/../../libreadline.so.6: undefined symbol: PC 

Any help appreciated.

Angela

**Comment by pmlandwehr** [comment]
Hmmm. Thanks for the note - can you try activating the environment, doing `conda install -c conda-forge readline`, and then running again? I'm thinking that the issue might be my linking the wrong readline library.

**Comment by angelaradulescu** [comment]
Thanks, that worked, new error though: 

> Traceback (most recent call last):
>   File "/home/angelar/envs/psiturk2/bin/psiturk", line 6, in <module>
>     sys.exit(psiturk.command_line.process())
>   File "/home/angelar/envs/psiturk2/lib/python2.7/site-packages/psiturk/command_line.py", line 15, in process
>     launch_shell()
>   File "/home/angelar/envs/psiturk2/lib/python2.7/site-packages/psiturk/command_line.py", line 111, in launch_shell
>     ps.run(cabinmode=args.cabinmode)
>   File "/home/angelar/envs/psiturk2/lib/python2.7/site-packages/psiturk/psiturk_shell.py", line 1889, in run
>     config.getboolean('Shell Parameters', 'launch_in_sandbox_mode'))
>   File "/home/angelar/envs/psiturk2/lib/python2.7/site-packages/psiturk/amt_services.py", line 304, in **init**
>     self.valid_login = self.verify_aws_login()
>   File "/home/angelar/envs/psiturk2/lib/python2.7/site-packages/psiturk/amt_services.py", line 491, in verify_aws_login
>     self.mtc = MTurkConnection(**mturkparams)
>   File "/home/angelar/envs/psiturk2/lib/python2.7/site-packages/boto/mturk/connection.py", line 61, in **init**
>     https_connection_factory)
>   File "/home/angelar/envs/psiturk2/lib/python2.7/site-packages/boto/connection.py", line 1033, in **init**
>     validate_certs=validate_certs)
>   File "/home/angelar/envs/psiturk2/lib/python2.7/site-packages/boto/connection.py", line 482, in **init**
>     "SSL server certificate validation is enabled in boto "
> boto.exception.BotoClientError: BotoClientError: SSL server certificate validation is enabled in boto configuration, but Python dependencies required to support this feature are not available. Certificate validation is only supported when running under Python 2.6 or later.

I tried to link boto again using the same trick you suggested above, and was asked to downgrade readline, which brought me back to the first error. 

But then, get this. Re-installed readline and now it's working!

**Comment by pmlandwehr** [comment]
Interesting. Well, I'll update the build with the other `readline`, so hopefully that should sort out the first issue. The other issue will require some additional hunting.
